@apiUrl= http://localhost:4002/api/v1

###
POST {{apiUrl}}/auth
Content-Type: application/json

{
  "firstName":"User",
  "lastName":"Users",
  "username":"user",
  "email": "user@gmail.com", 
  "password": "1234"
}

###
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com", 
  "password": "1234"
}

###
POST {{apiUrl}}/chats
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlcjFAZ21haWwuY29tIiwiaWF0IjoxNzYyMzI0MTk3LCJleHAiOjE3NjI0MTA1OTd9.fpC_cUgCk8K58JTBWXF9dAuxzJP-FtJv9BI7s-XvZO4

{
  "name":"Chat with tester main",
  "members":["69089cb440832bad0145d4f6"],
  "isGroup":false
}


###
POST {{apiUrl}}/messages
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlcjFAZ21haWwuY29tIiwiaWF0IjoxNzYyMjA5Njg1LCJleHAiOjE3NjIyOTYwODV9.sGkcYr1l9MJwYgFYIouL6QjmDQr00L4ziIQkkWoS11Q

{
  "chatId":"6908aabccfdc26984250923b",
  "text":"nice making friends with you"
}

###
GET {{apiUrl}}/messages/6908aabccfdc26984250923b
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlcjFAZ21haWwuY29tIiwiaWF0IjoxNzYyMjA5Njg1LCJleHAiOjE3NjIyOTYwODV9.sGkcYr1l9MJwYgFYIouL6QjmDQr00L4ziIQkkWoS11Q

{

}