@apiUrl= http://localhost:4002/api/v1

###
POST {{apiUrl}}/auth
Content-Type: application/json

{
  "firstName":"User",
  "lastName":"Users",
  "username":"user",
  "email": "user@gmail.com", 
  "password": "1234"
}

###
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "tester@gmail.com", 
  "password": "1234"
}

###
POST {{apiUrl}}/chats
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlckBnbWFpbC5jb20iLCJpYXQiOjE3NjIzOTYzODQsImV4cCI6MTc2MjQ4Mjc4NH0.oLSH9C4nS3YVh6Jt-5PCmfMmf6VkxNOseEt47KTy7yg

{
  "name":"Chat with user main",
  "members":["690b0659c34deea4270536fb"],
  "isGroup":false
}


###
POST {{apiUrl}}/messages
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlckBnbWFpbC5jb20iLCJpYXQiOjE3NjIzOTYzODQsImV4cCI6MTc2MjQ4Mjc4NH0.oLSH9C4nS3YVh6Jt-5PCmfMmf6VkxNOseEt47KTy7yg

{
  "chatId":"690c090742ab2019cee06399",
  "text":"heyy"
}

###
GET {{apiUrl}}/messages/6908aabccfdc26984250923b
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlcjFAZ21haWwuY29tIiwiaWF0IjoxNzYyMjA5Njg1LCJleHAiOjE3NjIyOTYwODV9.sGkcYr1l9MJwYgFYIouL6QjmDQr00L4ziIQkkWoS11Q

{

}